### ISSUE TITLE
Getting "This Site Can Not Be Reached" error 

### ISSUE THREAD

**Issue by SethuSenthil** [kzahel/web-server-chrome#102]
I wanted to test my website on other devices so I selected my website's folder and also enabled the options to show index.html, run in the background and Accessible on local network. On my Mac it works perfectly, but when I go into different devices it gives me This Site Can Not Be Reached error.

**Comment by kzahel** [comment]
If you are on a Wifi network sometimes there is "isolation" between different computers on that Wifi network. You might try and change your Wifi router settings.

Since you are running on Mac you might also try and disable your firewall (in system settings under Security there is a firewall tab)

**Comment by SethuSenthil** [comment]
@kzahel Thanks! Disabling the firewall worked!

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
