### ISSUE TITLE
cant open by https

### ISSUE THREAD

**Issue by cleverboy32** [kzahel/web-server-chrome#106]
i ready do the add to homescreen , and found this need request by https. but i input the url : https://127.0.0.1:8887,it cannt conncetion.  said 404

**Comment by SimplyCodin** [comment]
That's because the app dosen't support https

**Comment by kzahel** [comment]
If you weren't on chromeos you could use something like https://ngrok.com/ or localtunnel.
I could build something into the app but probably it would require some kind of sign in

**Comment by kzahel** [comment]
Duplicate of https://github.com/kzahel/web-server-chrome/issues/113
