### ISSUE TITLE
CORS-preflight request are not understood by the server

### ISSUE THREAD

**Issue by cyrilgandon** [kzahel/web-server-chrome#109]
Hi, I try to upload a file with a library ([angular-file-upload](https://github.com/nervgh/angular-file-upload)).

The library add a bunch of listener on the xhr object, which triggered a CORS-preflight request.

>The use-CORS-preflight flag being set is one of several conditions that results in a CORS-preflight request. The use-CORS-preflight flag is set if either one or more event listeners are registered on an XMLHttpRequestUpload object or if a ReadableStream object is used in a request.

[Source](https://fetch.spec.whatwg.org/#use-cors-preflight-flag)

A CORS-preflight request has not much of headers, particulary:

>A CORS-preflight request is a CORS request that checks to see if the CORS protocol is understood. It uses `OPTIONS` as method and includes these headers:

>`Access-Control-Request-Method`
Indicates which method a future CORS request to the same resource might use.

>`Access-Control-Request-Headers`
Indicates which headers a future CORS request to the same resource might use.

[Source](https://fetch.spec.whatwg.org/#cors-preflight-request)

Particulary, there is no `content-length` header, which is unfortunate, because this is the way `web-server-chrome` detects an OPTION request.

So at the end, I have the error:

> how to handle HTTPRequest {method: "OPTIONS", uri: "/repo/stuff.stuff", version: "HTTP/1.1", connection: HTTPConnection, headers: {…}, …}

Any idea how to handle those request?

**Comment by cyrilgandon** [comment]
I have removed those lines from the library:

	xhr.upload.onprogress = function (event) {
	};

	xhr.onload = function () {
	};

	xhr.onerror = function () {
	};

	xhr.onabort = function () {
	};

And it's working great. Unfortunately, I need those callbacks!

**Comment by kzahel** [comment]
Sorry I am not understanding exactly what the issue is. I included a CORS option and when enabled, and it sees an OPTIONS request, it responds with a 200 and with a few CORS headers.

Perhaps there is another method that needs to be in the allow-methods, for your use case, such as UPDATE, or PUT?
```
            this.setHeader('access-control-allow-origin','*')
            this.setHeader('access-control-allow-methods','GET, POST')
            this.setHeader('access-control-max-age','120')
```

**Comment by cyrilgandon** [comment]
Yes, I'm not sure anymore, I wonder if the problem comes from my side because I'm in a file:// origin.

I will investigate further and let you know!

**Comment by cyrilgandon** [comment]
I don't see any test for an 'OPTIONS' method.
What I see is when you drag and drop a file, you are making a PUT request, but since it is on the same origin, I guess Chrome didn't do a preflight request, the request is directly the right PUT request.

On the other hand, by trying to upload a file with CORS, Chrome first send a prefligth request with an OPTIONS methods. I looked everywhere, but OPTIONS is not tested.

The server stop here : [HTTPConnection.onHeaders](https://github.com/kzahel/web-server-chrome/blob/master/connection.js)

    if (method == 'GET') {
        this.onRequest(this.curRequest)
    } else if (method == 'HEAD') {
        this.onRequest(this.curRequest)
    } else if (method == 'PUT') {
        // handle request BODY?
        this.onRequest(this.curRequest)
    } else {
        // method == OPTIONS, error message
        console.error('how to handle',this.curRequest)
    }

Maybe I'm wrong, but I didn't found how the server is supposed to handle an OPTIONS request.

**Comment by kzahel** [comment]
can you test your code while adding in another test case for checking for OPTIONS?
I don't have a good minimal example way of testing CORS.
I could also just add in another check for checking for options method and do a release and you can test it from the web store version :-)

**Comment by kzahel** [comment]
Cool I'm able to reproduce.

```
<input id="input" type="file" />
<script>
function upload() {
var input = document.getElementById('input')
var file = input.files[0];
var fd = new FormData();
fd.append('file', file);
  function responseHandler(e) {
  console.log('readystate change',e)
  }
var xhr = new XMLHttpRequest();
xhr.open('PUT', 'http://127.0.0.1:8887', true);
xhr.onreadystatechange = responseHandler;
xhr.send(fd);
}
</script>
```
Should have a fix for you soon.

**Comment by kzahel** [comment]
Putting out an update to the store. When you get the update in the next few hours please test and let me know if it fixes your issue. (You can try to force update by going to `chrome://extensions` and clicking developer mode and pressing the "Update Extensions Now" button

https://github.com/kzahel/web-server-chrome/commit/56b1bd68e16925e45a42483f7a5b1127ea3c9958

**Comment by cyrilgandon** [comment]
Awesome, it'll have to wait until Monday, but I'll definitely check that, thank you!

**Comment by cyrilgandon** [comment]
Great fix, thank you!
