### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by jacksonhvisuals** [kzahel/web-server-chrome#113]
Now that Google requires HTTPS for many features for the web for Chrome, it would be quite nice to have an HTTPS option for the local server. 

I'm running an app that sends a notification (through the Notification API, not service workers), but since Chrome 61 or 62, Chrome blocks it because the local server ain't HTTPS.

**Comment by kzahel** [comment]
I see. Yes I have been thinking a little bit about how to do this. I think I have a solution that may work OK. I plan on hosting a DNS server that resolves {local-ip}.webserverchrome.org for example to {local-ip} and shipping the app with a wildcard certificate and using forge to serve HTTPS traffic from the app. It's the only workable solution I can think of (that works over LAN... for localhost only it would be somewhat simpler of course!)

**Comment by minjax** [comment]
Another vote for https:// serving of local files.

I'm looking for a solution to inject local files into a javascript/database app running over https:// and setting up a full Apache stack seems... excessive.

**Comment by SkateScout** [comment]
Hi is it possible to add support to an user provided key+certificate. Than any fqdn can be used via etc/hosts.

**Comment by ethanaobrien** [comment]
@kzahel Does this need to be closed?
