### ISSUE TITLE
Need a way to edit permissible MIME types

### ISSUE THREAD

**Issue by AskYous** [kzahel/web-server-chrome#133]
I'm trying to serve an mjs file but the browser rejects using it. It says:

`Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.`

**Comment by kzahel** [comment]
Would a process like this work for you...

```
- open chrome://inspect, inspect web server background page
- type WSC.addMimeType('mjs','application/javascript')
```
you would have to do this each time you install web server on a new computer.

**Comment by AskYous** [comment]
Yeah that would be fine. But ideally, it would be somewhere in the advanced settings:
![image](https://user-images.githubusercontent.com/791996/37066371-0215d9ea-215a-11e8-8d2f-8e4df0b1ce67.png)

That would make it easy and I can see the MIME types I added in case I forget they're there in the future. Appreciate your work!

**Comment by Sti2nd** [comment]
Just bumped into this issue.

The server could just support JavaScript modules by returning the correct MIME-type? Modules are coming, and they require correct MIME type https://developers.google.com/web/fundamentals/primers/modules

**Comment by aiden-w-135752345** [comment]
I guess something similar also needs to happen for .wasm to application/wasm.
`WSC.addMimeType('wasm','application/wasm')`
will this stay fixed after my Chromebook restarts?

**Comment by kzahel** [comment]
This will be included by default in the next release:

cb300b15 (Chris Chou    2019-02-25 20:32:53 +1300 875)   "wasm": "application/wasm", 
0329c4e3 (Ahmet Kizilay 2018-11-11 17:32:53 -0500 442)   "mjs": "application/javascript",
