### ISSUE TITLE
Closing app does not stop server

### ISSUE THREAD

**Issue by mattlockyer** [kzahel/web-server-chrome#14]
If you close the app the server appears to still run? There's no option to stop the server?

**Comment by isorna** [comment]
Any update on this issue? I'm using a chromebook, and only want to start the webserver on demand, but the server is working even with the chrome app closed, even with every other app closed the computer is working, and it didn't happened before installing web-server-chrome.

**Comment by kzahel** [comment]
Hi. I did add in a stop function but haven't put in the UI for it yet.
You can manually stop it by going to chrome://extensions and unchecking the
app there.
I will add a UI element to stop the server at some point...

**Comment by alantheprice** [comment]
+1 for Stop feature.

**Comment by kzahel** [comment]
Added this feature and released it, let me know how it works for you
