### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by abominab** [kzahel/web-server-chrome#141]
I'm following the Google tutorial for a PWA and when I try to get the server started I get an ERR_ACCESS_DENIED. Nothing I do in the options or restarting changes anything. I also tried running Chrome as an administrator to see if that changed things. It didn't. I'm on Windows.
![image](https://user-images.githubusercontent.com/10157407/38696508-9daa40f8-3e4c-11e8-8e7f-966b7ca5c6c0.png)

This is what I was following:
https://codelabs.developers.google.com/codelabs/your-first-pwapp/#1

**Comment by kzahel** [comment]
Can you try switching the port to something else like 8888 or 8889 and try to stop/start again?

**Comment by abominab** [comment]
8889 got it. That got me searching and I saw that there was another process using 8887. I'm surprised that gave an access denied error and not something else. Thanks for the help.
