### ISSUE TITLE
when starting the servers, page shows index.html

### ISSUE THREAD

**Issue by Elgoodcoin** [kzahel/web-server-chrome#145]
Hi

at step two of "your first progressiv web app"

when I click on the highlightened link http://127.0.0.1**** , the page doesn't show the waiting logo like in the course, but it actually shows the entire folder"your first progressiv web app"

what can I do about it?
![fireshot capture 2 - index of current directory - http___127 0 0 1_8887_](https://user-images.githubusercontent.com/34665757/40088232-767d938a-58a6-11e8-9639-124800c3681c.png)

**Comment by Elgoodcoin** [comment]
ok

when I clicked the link  I had what is shown up.

but if I click on the folder "work"index.html , it does show the app and waiting logo. 
so it works perfectly on next step.

**Comment by megdimka** [comment]
change directory to step-, work or final
