### ISSUE TITLE
Extension for Firefox

### ISSUE THREAD

**Issue by photopea** [kzahel/web-server-chrome#158]
Because the last update of Chrome 69 made all texts look blurry for me, I decided to switch to Firefox. But I still have to have Chrome on, because of this extension. Could you make the version of this extension, that could be used in Firefox?

**Comment by kzahel** [comment]
AFAIK this is not possible at the moment to implement in FF: See https://bugzilla.mozilla.org/show_bug.cgi?id=1247628

**Comment by photopea** [comment]
Ok, Chrome just fixed my problem, so I am using Chrome again.

**Comment by marimeireles** [comment]
Until we have access to to UDP and TCP sockets this extension wouldn't work on firefox?
(sry to comment on an old issue, but since it's still not resolved, should it be reopened?)

**Comment by ethanaobrien** [comment]
@marimeireles 

>Until we have access to to UDP and TCP sockets this extension wouldn't work on firefox?

Correct. 

You might want to try [this](https://github.com/terreng/simple-web-server). We re-wrote this project because chrome apps died

**Comment by marimeireles** [comment]
Thank you!
