### ISSUE TITLE
Support mime type for webassembly "application/wasm"

### ISSUE THREAD

**Issue by chhschou** [kzahel/web-server-chrome#166]
When requesting for a `.wasm` file there is no "content-type" in response header. Error in console is: `Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.`

Looks like mime type can be easily added to mime.js, like in this commit https://github.com/kzahel/web-server-chrome/pull/161/commits/0329c4e3de483c2a3f5b4a8efbd3c007acce0392

Want a PR for this?

**Comment by kzahel** [comment]
Sure. Thanks

**Comment by Demonrequest4u** [comment]
What is it I’m to do from watching this repository I’m very fresh to the screen of this all an know thou my goal is to gain I.T. Status capabilities by learning more network capabilities and remoting procedure abilities on the fly. Mainly an easier boot in process and chaining if keeping track an control of 12 to 15 units all of my own at this moment by myself what advice, all In one, or algorithm can suggest simply PLEASE. ANYTHING from good easy reads to a WHAt EVER!
