### ISSUE TITLE
Is it possible to serve files from the DOMfilesystem?

### ISSUE THREAD

**Issue by pier66** [kzahel/web-server-chrome#17]
I'm asking this because I'm wondering if it's possible to build a Chrome app which can open downloaded HTML content in a webview tag.

**Comment by kzahel** [comment]
I think they have the same API so yes this would be possible. However
aren't those domain specific?

**Comment by pier66** [comment]
Sorry, I don't understand what you mean by "domain specific".
I didn't find a way to access them through a "regular" URL which I could put in the src attribute of the webview tag. I can only get their content through the requestFileSystem API.

**Comment by kzahel** [comment]
Well I mean the DOM filesystem is typically tied to a domain like www.facebook.com has its own DOM filesystem. So the only way to get access to it is if you have access to host a javascript file on that domain. I can't think of any ways to work around this

**Comment by pier66** [comment]
OK. No, in my scenario the Chrome app would start the server serving the files of its own DOMfilesystem
and then opens them again in a webview tag. The server would simply act as the necessary link between the files and the webview tag.

**Comment by kzahel** [comment]
I think that should work fine. It would be a DOM filesystem hosted on http://127.0.0.1:{port} and the webview should be able to share it with a browser tab at the same URL.

**Comment by pier66** [comment]
I'm glad to hear this. Could your webserver be modified in a way to achieve this?

**Comment by pier66** [comment]
I got it! It was much simpler than I thought. I will create a fork. Thank you!
