### ISSUE TITLE
Embedded #include in content="" not recognized

### ISSUE THREAD

**Issue by debirieden** [kzahel/web-server-chrome#176]
The server is having issues parsing an "include" included in "content".  Not sure if the "quotes" are the issue.

Here is a snippet of the index.html file where the issue is occurring.

In the HEAD tag: 
```
<head>
...
<meta name="description" content="The Littleton Road Race is a 5k race and 1 mile fun run held on Sunday, <!--#include virtual="/includes/race_date.html" -->, at Fay Park in Littleton, Massachusetts.  The fun run begins at 2pm, with the 5k at 2:30pm."/>
...
</head>
```

The server is unable to see the embedded <!--include virtual="/includes/race_date.html"
It treats the first " as the end of content.
This causes the following to be included in the body of the html: ", at Fay Park in Littleton, Massachusetts.  The fun run begins at 2pm, with the 5k at 2:30pm."

In the "Elements" tab of the Chrome Developer Tools IDE, the following is displayed:

```
<head>
...
<meta name="description" content="The Littleton Road Race is a 5k race and 1 mile fun run held on Sunday,
<!--#include virtual=" includes race_date.html"-->
</head>
```

Notice 

- ", at Fay Park ..." is missing.

- the forward slashes are missing in /includes/race_date.html

On a different note, I LOVE THAT THERE IS A WEBSERVER for the Chromebook and developer tools.
Thank you!

**Comment by kzahel** [comment]
#include isn't a HTML spec. the web server only serves static files, and doesn't do any php or asp style processing.

If you want dynamic content your other option is to use javascript to load external data

**Comment by debirieden** [comment]
Okay, thank you.
I'll close out this request.
