### ISSUE TITLE
[Not Issue but Question] 

### ISSUE THREAD

**Issue by AlphaCircle** [kzahel/web-server-chrome#179]
Hello Chrome Web-Server

I am using your app for various purposes. I always appreciate your contribution and good will for world. 

While using this excellent app, I got a question about streaming protocol. What protocol is being utilized by this app? (I assume it is not HLS or DASH but more simple one.) I want to know the protocol you are using for this app.

Thanks
Alphacircle.

**Comment by kzahel** [comment]
It streams HTTP? Not sure what you mean exactly. When it is serving large movie files, it can serve small byte offsets of files if requested in the HTTP headers. Also for large files it does not try to read the entire file into memory and then send, but rather reads and writes chunk by chunk.

No fancy HLS or DASH protocols are used, just basic HTTP

**Comment by AlphaCircle** [comment]
Hello Kzahel
Thanks for your answer !!  Your answer is clear to me.

Thanks
Alphacircle
