### ISSUE TITLE
Some polymer error

### ISSUE THREAD

**Issue by adifbbk1** [kzahel/web-server-chrome#183]
![Screenshot 2019-06-26 at 10 13 34 PM](https://user-images.githubusercontent.com/18526984/60198648-b9ead200-985f-11e9-93e5-c43ceee1ed87.png)
Take a look on screenshot

**Comment by kzahel** [comment]
This happens when you run from source but dont run the build scripts.
I think the build scripts are no longer working as I am using deprecated versions of polymer.
I will have to rewrite the UI using react or something when time permits.
