### ISSUE TITLE
Its trying to load a different file then i have selected

### ISSUE THREAD

**Issue by Bradley1111** [kzahel/web-server-chrome#187]
i have been programming in js and ive been using this before hosting the program on a website and it was working fine until recently when it started trying to load a file i didnt have selected

**Comment by Bradley1111** [comment]
just figured it out problem fixed it was a mix of problems i could fix

**Comment by ecc521** [comment]
If this is not an issue with the server, and is rather one with your configuration, could you close this issue?

If this is a problem with the server, we will need a lot more information to attempt to debug this.
