### ISSUE TITLE
my browser error DNS maybe

### ISSUE THREAD

**Issue by allenspark** [kzahel/web-server-chrome#194]
this happen because i close my browser first then i close web server chrome ( second windows)

i already fix it my browser work but... now its come back and i cant work because cant acces my google drive :(

already clear browser history all, fix dns with cmd and still not work.

after i remove the extension its work but, i cant acces my google drive from my browser after clear history... help me.

![image](https://user-images.githubusercontent.com/20266377/67861807-7e387f80-fb53-11e9-85eb-4d5523582339.png)

**Comment by herysetyawan** [comment]
in the morning i opened my laptop and go to google drive its work. :)
