### ISSUE TITLE
document.registerElement is deprecated

### ISSUE THREAD

**Issue by StanNL** [kzahel/web-server-chrome#196]
As of Chrome 80, document.registerElement is deprecated and running Web Server for Chrome gives an error message in the console and the app itself doesn't work at all anymore sadly. It should be an easy fix I think/hope.

Thanks for the great work!

**Comment by kzahel** [comment]
Thanks for the heads up!

**Comment by sdwlig** [comment]
I've been developing a big app for the last 5 years using Polymer, 1.x, then 2.x, now switching to lit-element/lit-html.  I have a way of avoiding the need to run a build for 2.x or lit-element, and of course those are now updated to current browser standards.

I need something like this that has at least one additional feature:
I need a virtual path to cause a search (with caching) through a series of directories.  Ideally, this mapping should come from a .json file, like pathmapping.json.  I do this with nginx, including having certain directories caching and others non-caching.  I'm about to propose a standard pattern for this that solves a number of problems, especially allowing no-build web apps and solving the browser caching issues with .js files.  I'm going to publish a new web stack, propose this cache busting method along with a nice tool, and some other related things.  It would be nice to have this as an easier to install solution for the web server.

To go further toward what I need for this, it would be useful to have a certain path forward websocket or rest requests to a service running NodeJS code.  That's more complex, but could be interesting.

I may be able to create a fork and make these changes, but if anyone implements them first I would be very appreciative.

**Comment by kzahel** [comment]
Fixed
