### ISSUE TITLE
doesn't work on different networks

### ISSUE THREAD

**Issue by foorpyxof** [kzahel/web-server-chrome#197]
i made a webserver with a few files, but it only works on the same wifi network as i'm hosting the server on. for example: I made a server on chromebook and tried testing on phone, using mobile data so its a different network. I just get the error "This site cant be reached". any solutions?

**Comment by FreiBj** [comment]
Did you find a solution to this? Did you have to port forward the connection?

**Comment by wolfy01** [comment]
Seem to be having the same issue. Enabled port forwarding on my router for my pc, also tested accessing the port 8887 running something on nodejs to test it, worked fine. However, when using web server for chrome, I cannot access it anymore on an other network, I used to be able to until recently when I decided to use it again, I have tried other ports, that doesn't work either

**Comment by wolfy01** [comment]
This worked for me: https://github.com/kzahel/web-server-chrome/issues/58#issuecomment-584825412
except i added outbound as well as inbound

**Comment by FreiBj** [comment]
@wolfy01 Thanks, I'll look into it and try this out!
