### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by Linkstar75** [kzahel/web-server-chrome#20]
Hi, great App, it does exactly what i need. Just one wish: it would be great, if i could define, that the app starts automaticly at browser-start. Dont know, if this is possible in Chrome.

**Comment by kzahel** [comment]
It's possible if I made an extension that would send it a message to start up. It wouldn't be hard to do, but I'm curious why you want to do this

**Comment by Linkstar75** [comment]
I use some local html files in our intranet and for some reasons i dont understand, our admin blocked urls beginning with file://
So i found your app and now i can open the files beginning with http and all works fine.
But at the moment i have to start the server manualy before i can start using my local html-files.
It's not a big issue, but if it would be possible to define an autostart, i could be a very bit more lazy ;)

**Comment by kzahel** [comment]
which OS are you using? ChromeOS?

**Comment by Linkstar75** [comment]
No, Windows 7 (64Bit) with the newest Chrome (32 Bit)

2015-06-24 9:35 GMT+02:00 Kyle Graehl <notifications@github.com>:

**Comment by philxtian** [comment]
I guess it's better if the web server can run in background automatically when we open the browser.

**Comment by kzahel** [comment]
There is an option now to keep it running in the background, check it out and let me if it works.

**Comment by Linkstar75** [comment]
It runs in the background, if i open the settings dialog once. That works.

**Comment by bzimmerly** [comment]
1. Chromebooks automatically start the browser when the use logs in.
2. I have mine set to open one tab: 127.0.0.1:8080.
3. I have your web server set to port 8080 and have an index.html file set up.

The problem (we) would like solved is seeing the server automatically start without having to execute the web server - is this possible?

**Comment by bzimmerly** [comment]
1. Chromebooks automatically start the browser when the user logs in.

2. I have mine set to open one tab: 127.0.0.1:8080.

3. I have your web server set to port 8080 and have an index.html file set up.

The problem (we) would like solved is seeing the server automatically start without having to execute the web server - is this possible?

**Comment by kzahel** [comment]
I can see one way of accomplishing this. I could make a small extension
which causes the server to start. There may be a more elegant way of
accomplishing this, however. You can reach me directly kyke@graehlarts.com
if you want to prod me to make this happen faster

**Comment by bzimmerly** [comment]
Thanks Kyle! I look forward to it.   :)

Sincerely,
Bill
(Sent from my Galaxy Note 4 and GMail account.)

**Comment by kzahel** [comment]
Hi. I just put out a new version with a new option to auto start. Let me know if it works!

**Comment by bzimmerly** [comment]
Awesome, Kyle ... I'll try it out and report back to you. (I can't at the
moment, but will by the end of today.)

Sincerely,
Bill
(Sent from my GMail account)

**Comment by bzimmerly** [comment]
Hi Kyle!

I'm sorry for being so late, but the web server starts up perfectly. I just
needed to be patient.

- Bill


Sincerely,
Bill
(Sent from my GMail account)

**Comment by ethanaobrien** [comment]
@kzahel Should this be closed?
