### ISSUE TITLE
Cannot choose folder on Vivaldi on Windows 10

### ISSUE THREAD

**Issue by Betosaurus** [kzahel/web-server-chrome#200]
Hi, as by title, I tried to install the extension on the Vivaldi browser and if I press "Choose folder" it does nothing. I'm using Vivaldi 2.9.1705.41 (Stable channel) (a 32 bit).

**Comment by Viibrant** [comment]
I'm encountering the same issue with Vivaldi on Linux. I'm running 2.6.1566.44 (Stable channel) (64-bit)

**Comment by xchellx** [comment]
Here is console when clicking CHOOSE FOLDER:
`app created
index.js:163 fetched local settings AppOptions Object
index.js:202 webapp changed Object
index.js:202 webapp changed Object
index.js:202 webapp changed Object
DevTools failed to parse SourceMap: chrome-extension://ofhbbkphhbklhfoeikjpcbhemlocgigb/react-ui/nojsx/index.js.map
DevTools failed to parse SourceMap: chrome-extension://ofhbbkphhbklhfoeikjpcbhemlocgigb/react-ui/nojsx/options.js.map
index.js:219 clicked choose folder
index.html:1 Unchecked runtime.lastError: Invalid calling page. This function can't be called from a background page.`

**Comment by banderlog** [comment]
Same for Ubuntu 20.04 with Vivaldi 3.4.2066.76 (Stable channel) (64-bit)

**Comment by kzahel** [comment]
Should be fixed now

**Comment by banderlog** [comment]
>Should be fixed now
nope
