### ISSUE TITLE
How to render local Markdown files?

### ISSUE THREAD

**Issue by llinfeng** [kzahel/web-server-chrome#204]
Here is my current configuration and I keep a good number of Markdown files in the `/Warehouse` folder
![image](https://user-images.githubusercontent.com/5890407/73077476-3beeb800-3e8e-11ea-9dc5-e9bd3da6e4af.png)

How can I get the `*.md` files properly rendered when visiting through `http://127.0.0.1:8887/ssh.md`? **Is there a Chrome add-on that can help**? Here are three "views" of the same `ssh.md` file.

![image](https://user-images.githubusercontent.com/5890407/73078034-5c6b4200-3e8f-11ea-8f05-f451cf816927.png)

----

I was introduced to this app by [this post](https://www.reddit.com/r/todoist/comments/7zoabx/use_hyperlinks_to_link_to_local_file_folders/) and [this post](https://stackoverflow.com/questions/39007243/cannot-open-local-file-chrome-not-allowed-to-load-local-resource/46480984#46480984).

**Comment by BatDev0** [comment]
Just search markdown viewer install the extension then add it so it will have all website permissions on the extension settings.

**Comment by llinfeng** [comment]
Closing this issue as I ended up hosting my local markdown files through [`markserv`](https://github.com/markserv/markserv). No viewer/app needed anymore.
