### ISSUE TITLE
build instructions impossible?

### ISSUE THREAD

**Issue by over9001** [kzahel/web-server-chrome#205]
Hi! Thank you for making this available!

I'm trying to use this, and I want to build from source from this repo.
The new build instructions mention /makedeps/, which I don't see anywhere. https://github.com/kzahel/web-server-chrome/commit/d2b87cecb27775c98f3950a5c907bff90fc63d68#r36988916

May we please have the /makedeps/ scripts? Or some advice, please?

Thank you!

**Comment by kzahel** [comment]
Oops! Will add it in a few hours when I am home

**Comment by kzahel** [comment]
let me know if it works. i just pushed up the folder
