### ISSUE TITLE
Blank window with old chrome versions

### ISSUE THREAD

**Issue by dariop** [kzahel/web-server-chrome#207]
Hi,
I'm using last version of this extension (01.16.2020) on Google Chrome ver.57 (cannot update it for some reason) and with this version preferences windows is totally blank.
Thank you for this extension.

![unnamed](https://user-images.githubusercontent.com/2648531/73774867-0fd41080-4785-11ea-89aa-1cdaf9ca56db.png)

**Comment by kzahel** [comment]
I think this is because react version 16 doesn't support that version of chrome? Maybe you can upgrade?

**Comment by kzahel** [comment]
Or material ui. Can you check the console error. Look under chrome://inspect for the page

**Comment by dariop** [comment]
There's nothing in the console log. How can I help ?
That's what I see in Elements tab:

```html
<html style="overflow-y: auto">
  <head>
    <script src="../chromise.js"></script>
    <script src="../assets/bundle.js"></script> 
    <!-- scripts from "makedeps" -->
  </head>
  <body style="margin: 0">
    <div id="app"></div>
    <script type="module" src="nojsx/index.js"></script>
  </body>
</html>
```

**Comment by kzahel** [comment]
Ohhh. I think that version of chrome does not support script type module. Hmm

**Comment by kzahel** [comment]
I can add a fallback script type nomodule and have it use the old interface

**Comment by dariop** [comment]
Thank you, sounds good :)

**Comment by dariop** [comment]
I tried also with Chrome v66 (that should support script type module) but again, blank window

**Comment by BatDev0** [comment]
Maybe its just your chrome installation channel, I would suggest uninstalling your chrome browser. Reinstalling the regular or dev version again. Then trying the extension again. Reinstall the extension also.

**Comment by dariop** [comment]
I tried on a lot of computers with Chrome v66, and that windows was always blank...

**Comment by kzahel** [comment]
I won't add the fallback; upgrade chrome if you want to use it
