### ISSUE TITLE
Questions about this amazing tool

### ISSUE THREAD

**Issue by iblancasa** [kzahel/web-server-chrome#218]
I think this tool is amazing but I have some questions. Please, be patient because I'm new developing tools for Chrome and there are a lot of things I don't know about:
* Can this tool be added to a regular extension or must it be a Chrome application?
* Could you provide me with a minimal working example? I don't know what permissions do I need to set or what methods I need call

Thank you!
Again: this is amazing

**Comment by DamieFC** [comment]
I think it has to be a chrome application. I don't think you need to set anything, because I just went on the chrome web store, clicked add, it told me what it needed to do, you click accept I think, then it installs itself.

**Comment by kzahel** [comment]
It doesn't work as a regular extension
