### ISSUE TITLE
Not working properly with Vue.JS

### ISSUE THREAD

**Issue by eskayamadeus** [kzahel/web-server-chrome#228]
When I try to host my /dist folder after running npm run build, the server correctly shows the index page, but I'm not able to view other pages like login, register, dashboard or any others which I have already built.

For example, navigating to http://127.0.0.1:8887/login gives the "entry not found: /login" error.

How do I fix that?

**Comment by kzahel** [comment]
you might want to look in the advanced options at the Mod Rewrite (for SPA). If you search older (closed?) issues here you might also find some tips for how to use it. Sorry I am not really actively supporting this project anymore as chrome apps are being deprecated in the next years.
