### ISSUE TITLE
Android?

### ISSUE THREAD

**Issue by lborgman** [kzahel/web-server-chrome#230]
I'm looking for a safe web server that I can tell users to install on Android. With a safe default to just serve locally on the Android device.

And it must be easy to install. Like any app.

**Comment by kzahel** [comment]
That would be cool. I bet you can find many

**Comment by ethanaobrien** [comment]
@lborgman there is one called AWebServer. Link here - https://play.google.com/store/apps/details?id=com.sylkat.apache

Uses apache and supports php
