### ISSUE TITLE
App doesn't seem to work after building

### ISSUE THREAD

**Issue by wolfy01** [kzahel/web-server-chrome#231]
The app shows this: 
![image](https://user-images.githubusercontent.com/45273698/88912349-26878b80-d22d-11ea-97e6-aa7380332aa7.png)

and if I go to "Extensions" then "Chrome Apps" it shows this error: 
![image](https://user-images.githubusercontent.com/45273698/88912402-3606d480-d22d-11ea-8759-a73202bf180c.png)

No idea why cromise is not defined

**Comment by kzahel** [comment]
Thanks I forgot to commit a file (chromise.js) pull again and re-try

**Comment by Jayluv81** [comment]
gitch
