### ISSUE TITLE
PHP does not work with in my server (.phtml)

### ISSUE THREAD

**Issue by Ring-Games-Official** [kzahel/web-server-chrome#235]
I can not use PHP in PHTML with this server and am very annoyed. I recently got this (today) and used it only to use PHP to test my form.

I like this though
Using: Chrome OS 64-Bit
Version: Chrome 76

![image](https://user-images.githubusercontent.com/70617006/91925137-bed6cb80-ed17-11ea-8a70-9ba2d04f66dc.png)

**Comment by DamieFC** [comment]
Interesting. I noticed that it wouldn't let me set cookies with PHP, so I'm not sure. What happened with me though, was I tried to add cookies by putting the code in the `<head></head>` tags, and it said "Google Chrome OS cannot open this page".

**Comment by kzahel** [comment]
It can't do PHP
