### ISSUE TITLE
how to change the port?

### ISSUE THREAD

**Issue by wzshuang** [kzahel/web-server-chrome#24]
I installed the app from chrome webstore, but I found that there is no way to set the port number.

**Comment by alas** [comment]
me neither, so i added that and created a pull request:

https://github.com/kzahel/web-server-chrome/pull/27

if you need it right now you can download my version and manually add to chrome goto chrome://extensions/ enable developer mode and load it from directory, cheers

**Comment by kzahel** [comment]
Thanks! I merged it in. I'll release a new version soon

**Comment by alas** [comment]
youre awesome :)

**Comment by wzshuang** [comment]
thank you guys

**Comment by kzahel** [comment]
Released version to store. let me know if it works for ya

**Comment by alas** [comment]
it shows version 0.2.0 with no changes, maybe tomorrow it wll be updated, stores...

**Comment by kzahel** [comment]
It can take an hour or so. I see 0.2.1 on the store now

**Comment by alas** [comment]
works great, only thing I noticed now is if you have more than one ip they appear in the same line

![image](https://cloud.githubusercontent.com/assets/2131814/10171868/9cdd312c-66b2-11e5-8a34-1fbf8ed2146e.png)

**Comment by kzahel** [comment]
Yeah, the whole interface needs re-doing :-) it's VERY ugly...

**Comment by kzahel** [comment]
![screenshot 2015-10-01 at 1 43 39 pm](https://cloud.githubusercontent.com/assets/158352/10233288/78026980-6842-11e5-8ee5-e06d7cd5c4e1.png)

New interface, woo!
