### ISSUE TITLE
Folder Selecting Button is not working

### ISSUE THREAD

**Issue by ybhwang** [kzahel/web-server-chrome#257]
`Choose Folder` is not working.

- Device: Apple Mac mini with M1 (Silicon Mac)

**Comment by ethanaobrien** [comment]
@YBHwang Sorry for the delay, Please go to `chrome://extensions` find the web server app and click `details`. Scroll to the bottom and turn on the option `Collect errors`. Then go back, turn the extension off and then back on. Open the app, attempt to click `Choose Folder`, then go to `chrome://extensions` and next to the extension it should say `Errors`. Click this button and copy and paste every error you have.

**Comment by ybhwang** [comment]
It is working normally.
