### ISSUE TITLE
Displays code not serving

### ISSUE THREAD

**Issue by howedav** [kzahel/web-server-chrome#265]
Hi,
New to Chrome, learning php. Installed OK this extension and selected a local folder with one php file in it. Clicked link to folder and see file listed. Click and it only shows my code. Does this only serve html?

**Comment by ethanaobrien** [comment]
Welcome! only html and JavaScript is supported. Sorry! I found out the hard way too.

**Comment by howedav** [comment]
Thanks. Are you aware of any Chrome servers that do pHp?

**Comment by ethanaobrien** [comment]
I am not aware of any chrome extensions that use php. What os are you on. There are web servers (That support php) for android (yes, on your phone), windows, and linux

**Comment by howedav** [comment]
I have an iMac with MAMP so no problem when I can be in the office. But during certain hours I am in the kitchen minding stoves and food and was hoping to do more than watch cat videos. So I have Caret to edit the code but will have to figure out how to get to my cloud server to check progress. Thanks for help. Closing this out and bye.......

**Comment by ethanaobrien** [comment]
@pdwilso Cool. Yeah, chrombooks support a container known as crostini. This container runs debian buster. That would be PHP on chrome os. If you have questions about chrome os crostini - ask me. I know a lot. I would recomend downloading xampp - it is simple to use and has apache (with php), tomcat and a few other things and it's pretty cool. The only downside is that it does not give you the addresses you are serving on - It is possible to access from chrome os but you must run the command to sow the system ip address, then go to this url on your chromebook. It is really cool!

P.S. You might want this - Assuming you have more than 8gb storage like I do
`sudo dpkg --add-architecture i386 && sudo apt update && sudo apt install wine wine32`
