### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by InfMedElo** [kzahel/web-server-chrome#270]
Hi, I am using the app on Google Chrome version 90.0.4430.93
I have tried to create a public link with a project on it. The link opens up the project on my computer well but when I try and share the link to others even after selecting "Accessible on local network" and "Also on internet" the link does not seem to open up on the other computer that is also running the same version of Google Chrome that I have. Any advice as to what I should do?

**Comment by ethanaobrien** [comment]
@InfMedElo Please post a screenshot, I don't quite get what you mean. Please also post your os. There is a bug in the latest version (Pull request #264 fixes it) and yeah. (My pull request also has many more features)

**Comment by InfMedElo** [comment]
For sure, so this is a screenshot of my current settings. 
![Capture](https://user-images.githubusercontent.com/83606395/116917336-c1255880-ac0b-11eb-9d43-c4b70c8c1f13.PNG)
Essentially what is happening is when I click on any of those links while I am on my computer it will appear just fine. But whenever I try to share those links with a computer that is even next to mine it says "This site can’t be reached.. (numbers) refused to connect"
As far as my OS goes , my processor is 3970X 32-Core
my Ram is 64GB. 
If you need anything else from me please let me know

**Comment by ethanaobrien** [comment]
@InfMedElo When I said os I kinda meant like linux, windows, chrome os. I have enough info to answer though.

the 0.0.0.0:8888 and 127.0.0.1:8888 url will ONLY be accessible on your computer
the 10.0.0.234:8888 url should be accessible to any device on your local network.
The option to put it on the internet seems to only work on chrome os. You will need to go to 10.0.0.1 and configure port forwarding. the 10.0.0.234:8888 url is the one that you would forward. Then go to something like https://www.ipchicken.com/ and it will give your ip address. Open a new tab, go to your ip address and for example 12.34.455.567 you would need to add whatever port you configured on your router to be available on the outside so if you said port 8888 you would go to 12.34.455.567:8888

If you have any questions, ask me.

**Comment by InfMedElo** [comment]
Okay sorry 2 questions, first one is that I downloaded the patch #264 and got errors. The app still works, here is a screenshot of what I got. Should I do anything about it or is it okay?
![Capture](https://user-images.githubusercontent.com/83606395/116919786-07c88200-ac0f-11eb-8f52-6a0fcbcc1dcd.PNG)

Second question, so if I understood right, on my Windows computer I can just put my IPD address 12.34.455.567:8888 and then I should be able to share that link with any other device that I give the link to? Or does the device have to be connected to my Windows computer?

**Comment by ethanaobrien** [comment]
Q1 answer: Yeah, the errors are fine. They are still there before, but google chrome does not collect error for extensions downloaded from the chrome web store.

Q2 answer: Kind of. You must enable port forwarding on your router (For a more specific instruction get the model of your router and look up 'enterrouternamehere port forwarding'). Once you do this, anyone can access across the world.

If you have questions, just ask me!

**Comment by InfMedElo** [comment]
Awesome thank you for your responses

**Comment by ethanaobrien** [comment]
@InfMedElo Just so you know, I found a big bug in one of the features I put in on my pull request (#264 ). Please update the app. Just re download the zip and delete the directory where you extracted the zip last time and remove the app from `chrome://extensions`. Extract the new zip, and load unpacked from `chrome://extensions`. If you dont want the errors to show like you asked in the screenshot, press details and turn off the collect errors option (Toward bottom)
Thank you for testing my pull request!!

If your issue is solved, please close this issue

**Comment by InfMedElo** [comment]
@ethanaobrien Quick question! Is there any way to do more than one link? What I mean by that is that from what I can tell You can create a project by selecting a folder and that creates a link for that project. But the moment you switch folders the link you created for the previous project is "expired". Is there a way to keep the old link for the old project and a new link for the new project without having either become expired?

**Comment by ethanaobrien** [comment]
@InfMedElo 
When you change directories, you keep the same link (You dont even need to restart the web server). The link should be the same. It the port tries to change, then change it back.

Are you asking if you can serve more than 1 folder at a time?

**Comment by InfMedElo** [comment]
I suppose yes, because right now the link works for one folder at a time. Hope that makes sense. Thanks again for your help

**Comment by ethanaobrien** [comment]
Yes, that makes sense. Currently that is not possible (see #111 ) But there is a way around this.

Download this
https://drive.google.com/file/d/1GN2qQls1Lho8I1lB1vuOfuz5KxRPh3A9/view?usp=sharing

**Comment by InfMedElo** [comment]
Gotcha! Cool thanks I'll try it out. Out of curiosity is there going to be a feature in the future where you can select different folders without having to install the app multiple times?

**Comment by ethanaobrien** [comment]
@InfMedElo Probably not. I dont quite understand the app enough on how to listen on multiple ports. I may look into this later!

**Comment by InfMedElo** [comment]
Okay cool no worries! Thanks again for your help you've been great!

**Comment by ethanaobrien** [comment]
@InfMedElo 
Hey! Final Comment (Do like a thumbs up so I know you got it) I found a bug with the 404.html mimetype and a mimetype error with the exclude .html extension. I have fixed these bugs. The no cws id can be downloaded from here (The old link wont work)
https://drive.google.com/file/d/1Ct8cFd0xLnBKZi8jTUz4vY13FqkrzbOg/view?usp=sharing
And the link in the pull request is up to date!
