### ISSUE TITLE
It is not convenient to run server

### ISSUE THREAD

**Issue by Dragon-0609** [kzahel/web-server-chrome#281]
The extension works fine, but it's problem to run it. To run, you need to go to the chrome webstore, find the extension and in the end, press Run.
It is not convenient to run all the time. It will be better if window of server would be shown after the icon of web server pressed.

**Comment by ethanaobrien** [comment]
@Dragon-0609 This is a chrome app, not an extension. Go to [chrome://apps](chrome://apps)

**Comment by Dragon-0609** [comment]
Thanks, I didn't know about it.

**Comment by Dragon-0609** [comment]
Thanks, I didn't know about it.
