### ISSUE TITLE
Cannot wget a 3.5GB file from this webserver

### ISSUE THREAD

**Issue by spliskamatyshak** [kzahel/web-server-chrome#29]
I'm using this excellent little webserver for chef development and I believe I found a file too big for this webserver to serve. I've successfully done wget from VMs for files up to ~2.9GB, but I have a file that is 3.5GB that comes across as 0 size on the VMs.

Below is the 2.9GB file:
$ wget http://#.#.#.#:8887/oracleHome121024ee.tgz
--2015-10-22 20:00:33--  http://#.#.#.#:8887/oracleHome121024ee.tgz
Connecting to #.#.#.#:8887... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3141285114 (2.9G)
Saving to: “oracleHome121024ee.tgz”

 0% [                                                                                           ] 16,584,957  2.21M/s  eta 25m 23s ♥

Following is the 3.5GB file
$ wget http://#.#.#.#:8887/gridHome121024.tgz
--2015-10-22 20:11:02--  http://#.#.#.#:8887/gridHome121024.tgz
Connecting to #.#.#.#:8887... connected.
HTTP request sent, awaiting response... 200 OK
Length: 0
Saving to: “gridHome121024.tgz”

    [ <=>                                                                                       ] 0           --.-K/s   in 0s

2015-10-22 20:11:02 (0.00 B/s) - “gridHome121024.tgz” saved [0/0]

The 3.5GB file successfully downloads from a webdav, but it is horribly slow compared to having this happen between two SSDs on my workstation.

Any chance of removing or bumping up this limit?

**Comment by kzahel** [comment]
Very interesting!
Strange that it shows Length: 0
What is the filesystem type that is serving? Which OS?
Could possibly be a chrome filesystem api bug.
I will have to test on some large files :-)

**Comment by spliskamatyshak** [comment]
I'm running Oracle Linux 6.7 with UEK from a vagrant box created with Virtual Box.  The file system is virtual scsi ext4 partitions

**Comment by kzahel** [comment]
```
dd if=/dev/zero of=4g.img bs=1 count=0 seek=4194304000
wget http://127.0.0.1:8887/4g.img
--2015-10-22 14:04:02--  http://127.0.0.1:8887/4g.img
Connecting to 127.0.0.1:8887... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4194304000 (3.9G)
Saving to: '4g.img.1'

4g.img.1                                   1%[>                                                                                 ]  66.32M  7.12MB/s   eta 8m 55s
```

For >4GB file it seems to be working fine, sends the full length. I just tested on OSX running the web server

**Comment by spliskamatyshak** [comment]
I re-installed the web server. It is working fine know.

$ wget http://3.62.72.4:8887/gridHome121024.tgz
--2015-10-22 22:13:47--  http://3.62.72.4:8887/gridHome121024.tgz
Connecting to 3.62.72.4:8887... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3780027192 (3.5G)
Saving to: “gridHome121024.tgz”

 0% [                                                                                           ] 36,508,205   611K/s  eta 1h 50m

**Comment by spliskamatyshak** [comment]
Didn't have the latest and greatest.

**Comment by kzahel** [comment]
Might have been the file metadata cache bug
