### ISSUE TITLE
Specifying index.html

### ISSUE THREAD

**Issue by chrisritterc9** [kzahel/web-server-chrome#3]
Any hope on specifying the index.html

**Comment by kylecordes** [comment]
The simplest good approach to this would be to serve $whatever/index.html when $whatever/ is requested. A more sophisticated approach would be to have a configurable list of default files to serve, like most other web servers.

**Comment by kzahel** [comment]
https://github.com/kzahel/web-server-chrome/blob/master/handlers.js#L167
looks like I put in this feature but forgot to make a UI option for it. should be easy enough to put it in

**Comment by kylecordes** [comment]
Thanks!

**Comment by kzahel** [comment]
https://github.com/kzahel/web-server-chrome/commit/ef78dacc4caca1b4173caf92aedd031d5f858ce4
put in the UI for it and put on the store

**Comment by ijaaz** [comment]
There seems to be issues when you edit the index.html. The server stops workin' :(

**Comment by kzahel** [comment]
Hmm... I just tested a little now.
Any chance you could see what the error is for me?
type "chrome://inspect" into the URL, go to apps, look for background page for web server for chrome, and then click on Console, and see if any suspicious errors are appearing...
