### ISSUE TITLE
Error downloading item with long  file name.

### ISSUE THREAD

**Issue by trittell** [kzahel/web-server-chrome#35]
The webpage at http://192.168.1.66:8887/Sea-Story%20Megapack_%2030%20Classic%20Nautical%20Works%2C%20The%20-%20Jules%20Verne%20%26%20Jack%20Williamson%20%26%20Morgan%20Robertson.epub might be temporarily down or it may have moved permanently to a new web address.

[Philip K. Dick MEGAPACK TM, The - Philip K. Dick.zip](https://github.com/kzahel/web-server-chrome/files/61429/Philip.K.Dick.MEGAPACK.TM.The.-.Philip.K.Dick.zip)

**Comment by kzahel** [comment]
Weird. decodeURI("%2C%20") -> "%2C "

It is not decoding the %2C as a comma, so it is not finding the file

**Comment by kzahel** [comment]
Ah, I guess I should be using decodeURIComponent. Thanks for reporting this.

**Comment by kzahel** [comment]
https://github.com/kzahel/web-server-chrome/commit/209fb5ea16239dff67573c2ec8a7c72db5b09c80

**Comment by kzahel** [comment]
put 0.2.6 to web store, should see update soon.
