### ISSUE TITLE
Linux, Unable to bind port 80, and ...

### ISSUE THREAD

**Issue by izuolan** [kzahel/web-server-chrome#44]
Unable to bind port 80

and after close window will warning: 

![](http://i.imgur.com/p0NIYOP.png)

There is no warning before updating

Linux Ubuntu

**Comment by kzahel** [comment]
Hi. You need to disable either "background mode" and "accessible over network" to make that window go away.

**Comment by kzahel** [comment]
Also ports under 1024 are for administrator/root previlege processes only, so you need to pick a number over that.

**Comment by izuolan** [comment]
Yes. I know.
