### ISSUE TITLE
Support for CORS option?

### ISSUE THREAD

**Issue by mm-gmbd** [kzahel/web-server-chrome#49]
No support for CORS is making this would-be-great extension a bummer!

**Comment by kzahel** [comment]
I added an option for it but didn't make it a check box yet. Maybe just
turn it onby default? What do you need cors for?

**Comment by mm-gmbd** [comment]
I've got a web page that I'm hosting locally (using the chrome web server), and that page should load data from the filesystem (there is an input field on the page where you can input "file:///path/to/file"). Without CORS enabled, I cannot load the data from these files in Chrome without executing Chrome without a few special flags (that I would like to avoid).

**Comment by mm-gmbd** [comment]
I could definitely see it being a checkbox that is on by default. BTW - thanks for the cool tool!

**Comment by kzahel** [comment]
I didn't realize CORS headers would allow this. I am only setting Access-Control-Allow-Origin: * header, I think I remember there were some other special cors headers

**Comment by kzahel** [comment]
https://github.com/kzahel/web-server-chrome/issues/51 I'll add this into the options when I get to making the next update

**Comment by mm-gmbd** [comment]
Great! Thanks for the support

**Comment by domdomegg** [comment]
Done, this issue should be closed now

**Comment by ethanaobrien** [comment]
@kzahel should this be closed?

**Comment by mm-gmbd** [comment]
@kzahel Just got a notification as I'm the author of this issue. While it seems like the issue should probably be closed, just wanted to say apologies for the insensitive language in my original comment:

> No support for CORS is making this would-be-great extension **a bummer**!

Definitely not a bummer, I simply should have made the suggestion as a potential improvement. Thanks again for the great tool!

**Comment by kzahel** [comment]
Haha, I disagree it was a bummer :-) But thank you for your thoughtfulness
