### ISSUE TITLE
Problem with the server

### ISSUE THREAD

**Issue by hibratt** [kzahel/web-server-chrome#59]
The instruction says: 

![image](https://cloud.githubusercontent.com/assets/6505785/16260744/043c8ab0-3869-11e6-81c4-cc7e7d9879b5.png)

When I click on the URLid (http://127.0.0.1:8887/) I do not get a blank page but this:

![image](https://cloud.githubusercontent.com/assets/6505785/16260676/ba70499e-3868-11e6-863d-d340b43a985b.png)

What schould I do?

**Comment by kzahel** [comment]
Do you have js disabled? Add ?static=1 to the URL if so

**Comment by Blue-EyesWhiteDragon** [comment]
Just browsing through the issues here, and the answer to this old question is that the image shown has no index.html or index.htm within the directory.
