### ISSUE TITLE
Chrome max sockets reached when serving video

### ISSUE THREAD

**Issue by jschr** [kzahel/web-server-chrome#63]
First off, thanks for this library it's been a life saver for me. I'm embedding it in my chrome packaged app which allows you to setup a kiosk for any URL while providing an offline SDK that can be used to download images/video to the local machine which are then served through the local web server to the webview content (using html5 video element). I had attempted my own version a while ago and failed miserably until I came across this lib :). 

In one instance of a kiosk I am running a video loop where users can also click around and browse these videos. I am noticing that after some use (mostly when the user is clicking around) that the web server will stop serving the videos. When inspecting chrome://net-internals/#sockets I can see that the problem occurs when the active sockets for the web server reaches chrome's max limit of 6 per domain:

![image](https://cloud.githubusercontent.com/assets/1163252/17591195/0f2ef502-5fab-11e6-9691-6e58da8bfbde.png)

This seems to suggest that somehow sockets aren't being released even though my application should only be playing 2-3 videos at a time. 

I'm not sure if this is necessarily an issue with this library or my own code. I've tried to make sure that when a user selects a video to play, the old video element is removed but this did not seem to help. I also tried adding my own health check endpoint to the web server which gets pinged every 5s and will restart the web server if it times out - this also did not seem to release the sockets. The only thing that released the sockets was restarting the app.

Has anyone run into this issue before or could potentially offer some advice on how to debug this further?

**Comment by kzahel** [comment]
Sounds like a cool app!

I have not used the library in such an intensive environment, so good on you for pushing the boundaries :-)

It sounds to me like there are indeed some open and possibly inactive sockets

```
function debugSockets() {
    chrome.sockets.tcp.getSockets( function(socketInfos) {
        var d = {}
        for (var i=0; i<socketInfos.length; i++) {
            d[socketInfos[i].socketId] = socketInfos[i]
        }
        console.log('current tcp sockets',d)
    })
    chrome.sockets.tcpServer.getSockets( function(socketInfos) {
        var d = {}
        for (var i=0; i<socketInfos.length; i++) {
            d[socketInfos[i].socketId] = socketInfos[i]
        }
        console.log('current tcpServer sockets',d)
    })
    chrome.sockets.udp.getSockets( function(socketInfos) {
        var d = {}
        for (var i=0; i<socketInfos.length; i++) {
            d[socketInfos[i].socketId] = socketInfos[i]
        }
        console.log('current udp sockets',d)
    })
}
```

You might want to turn on WSC.DEBUG=true, WSC.VERBOSE=true

If it's possible for you to create a small html page with some videos and either general instructions or even automated click-like events for how to reproduce it, I bet I could fix it... but nothing really jumps to mind.

**Comment by jschr** [comment]
Thanks for the quick response. Working on a small test page as I type this but a bit of an update... 

I've been able to reproduce this on my machine (OSX) and an Ubuntu box but so far not ChromeOS. I also tried pointing the videos to remote URLs instead of serving through the local web server and noticed that I could eventually cause the video the hang for up to 10-20s trying to load if I repeatedly recreated the video element and removed it. Even the local web server would hang forever, it's starting to seem like the issue is probably out of scope of your lib (possibly good news for you... but not for me haha). 

I'm still debugging and will post back with a test page and more details.

**Comment by kzahel** [comment]
If you can, compare with nginx or apache, too. I bet those won't hiccup at all... which would mean it is a problem with WSC..

**Comment by jschr** [comment]
Ok so I think I've stumbled upon a bug in chrome. 

I'm able to consistently reproduce the issue on my machine (OSX) using this test page: 
http://chrome-video-socket-issue.s3-website-us-east-1.amazonaws.com. [Download from here](https://s3.amazonaws.com/chrome-video-socket-issue/source.zip).

I set up a local server using your chrome extension as well as hosted the videos on an s3 website and the issue happens with both. If you're curious and would like to reproduce, uncheck 'Local' and check 'Remote' on the test page then check 'Simulate user input'. By the 7th video the video will hang and you'll see a pending request in the Network tab that never finishes. 

Interestingly enough, when you check 'reuse video element' the issue doesn't happen. Inspecting chrome://net-internals#sockets I can see that when recreating the video element the sockets reach the max active limit of 6 but chrome seems to re-use the socket connection if you're just changing the src attribute of the same video element.

Chrome seems to not be releasing the socket connections when destroying the video element, which I can't imagine is expected behaviour. By all means close this issue if you agree and I'll file a chromium bug report. 

Appreciate the help regardless.

**Comment by kzahel** [comment]
I loaded your test page in windows 10 stable chrome and it's definitely behaving badly. I get what you mean with the 6 connections open.
You're not able to write some code to limit to 5 videos? Manually call .stop() on the video? It seems .empty() in not cleaning up the video socket. very interesting...

**Comment by kzahel** [comment]
There also seems to be a problem with 2.mp4, the metadata is invalid and i cannot seek past a certain point

**Comment by jschr** [comment]
I'm working on converting the app to reuse a single video element instead of recreating it which will hopefully solve my problem for now. I'll definitely need to keep this in mind if I ever want to display more than a few videos at a time. Thanks for the heads up about 2.mp4, maybe a bad upload but will look into it. Also thanks for confirming the issue happens on windows as well. 

Will close since really doubt there's much to do beyond filling a chromium issue at this point. Will hopefully get to that tomorrow and post a link back here for future reference.

**Comment by kzahel** [comment]
I'm definitely seeing that the video element is not closing the socket even when the video has been removed or manually called .stop(), so it does look like a chrome problem to me too

**Comment by kzahel** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=560477

**Comment by kzahel** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=162627

**Comment by kzahel** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=162627#c36 -- basically they say the media network code is old and crufty and nobody wants to touch it really, so if you want it to work correctly you need to use media source extensions :-)

**Comment by jschr** [comment]
Haha not a good sign that it's been open since 2012. I had a glimmer of hope that preload="auto" or preload="none" might workaround the issue but no dice! 

I may still file an issue since in my case I'm not actually trying to display 6 videos (or audio) at the same time... it's just not cleaning up properly when the DOM element is removed. I'll at least feel like I've done everything I can and will focus on the workarounds. 

Reusing the video element is probably the easiest workaround for the app that's having the issue. From my research you can probably also workaround it by using websockets and/or the (media source)[http://html5-demos.appspot.com/static/media-source.html] extension (as you pointed out).

**Comment by jschr** [comment]
FWIW I've been testing WSC pretty heavily with serving up video. I got a couple of chromebits and a chromebox that's been looping through ~2GBs of video 24/7 without any issues. So kudos to you :)

**Comment by kzahel** [comment]
Good to hear! Do you have a webstore link?

**Comment by jschr** [comment]
Not yet. Currently still in development and tied to our app's backend right now. I want to make a general version though which would let you use any URL (or maybe github project) as a kiosk with an api to help make offline apps. There's a similar app on the store now. Initially tried Electron but wanted to use ChromeOS and WSC is basically the only reason we could :P

**Comment by kzahel** [comment]
How do you install chrome apps without webstore? you mean it's a private webstore link? I thought chrome took away the ability to manually install apps/extensions (unless you have enterprise / google app for work policy thing ? )

**Comment by jschr** [comment]
Ya you used to be able to manually install the .crx package but pretty sure they took that away as well. I'm using an unlisted link at the moment for testing. You can also force install apps like you said for managed devices.

**Comment by kzahel** [comment]
That's what I thought. Bummer. I am trying to find out a solution for installing apps/extensions in completely offline / isolated environment (in a prison) ... sucks that they took away the update_url thing

**Comment by jschr** [comment]
Ya that sucks. If they're completely offline can't they be preinstalled on the device? I guess you'll still want to be able to update them somehow even when offline? ChromeOS has been pretty reliable for us (Chromebits/Chromebook specifically) so that's why we moved back but unfortunately you have to tradeoff pretty much any customizability. I'm still waiting for a reliable way to hide the damn cursor and change wifi from my app (both are terrible for any kiosk environment).

**Comment by kzahel** [comment]
I can indeed preinstall. But then there's no way to update. Unless I made my own update mechanism... by downloading updated code, but then i'd only be able to run updated code in a sandbox... postMessage + eval weird magickery would maybe make it work.

Looks like the wifi API is in the works for kiosk apps at least https://bugs.chromium.org/p/chromium/issues/detail?id=344908

**Comment by jschr** [comment]
Nice, been following that issue for a while but looks like they've made some recent progress. Looking forward to that since right now users have to shift-alt-s on startup to get the OS, change the wifi then restart the kiosk.

I'm actually doing something similar in my app with regards to offline right now. The app itself is essentially just a shell that loads a URL into a webview for the actual kiosk content. With a service worker I can make the content offline. Then theres a small sdk that the content can use (all done via post message) to tell the kiosk to download additional resources to make it fully offline. Took quite a bit of trial and error though, Chrome really wants you to package all resources with the actual app. Happy to share more details, I think it would be pretty straight forward to load the content from an external USB instead of a URL. Although still not sure how you can update the shell without an internet connection unfortunately... Sounds like an interesting project at least.

**Comment by jschr** [comment]
Submitted a chromium issue for this: https://bugs.chromium.org/p/chromium/issues/detail?id=637284
