### ISSUE TITLE
FileError has been removed from Chrome Canary 

### ISSUE THREAD

**Issue by greenjeffreym** [kzahel/web-server-chrome#65]
The handlers.js file uses FileError for error checking, but this is an obsolete feature. It has also been removed from Chrome 54 (latest Canary). I can be replaced with DOMError.

**Comment by kzahel** [comment]
Ah cool I'll look into this later. Thanks for the heads up

**Comment by kzahel** [comment]
Thanks. I fixed it.
https://github.com/kzahel/web-server-chrome/commit/f22a394a9aa1f3bf5154c4918a97fa64e852f4fe
