### ISSUE TITLE
Scripts are not Loaded from Symbolic Link Directories (macOS)

### ISSUE THREAD

**Issue by evs-hw** [kzahel/web-server-chrome#67]
Repeat:
1. Have some JavaScript code somewhere (like /git)
2. Have your www directory somewhere else (like /www)
3. Create a symbolic link (ln -s) to the JavaScript directory, e.g. cd /www; ln -s /git link-to-git-folder
4. Try to load a .js file via `<script src="js/link-to-git-folder/script.js">` within index.html

**Comment by kzahel** [comment]
Looks like this is a known issue with another app: https://github.com/GoogleChrome/chromedeveditor/issues/3102

**Comment by evs-hw** [comment]
OK, that clears things up. Thanks!
