### ISSUE TITLE
cant access index.html

### ISSUE THREAD

**Issue by scheng123** [kzahel/web-server-chrome#69]
it keeps loading forever

**Comment by kzahel** [comment]
Can you provide OS, versions, etc. ?
e.g. go to chrome://version and provide that info

**Comment by scheng123** [comment]
Google Inc.
Copyright 2016 Google Inc. All rights reserved.
Google Chrome	55.0.2858.0 (Official Build) dev (64-bit)
Revision	0
Platform	8798.0.0 (Official Build) dev-channel candy
JavaScript	V8 5.5.149
Flash	23.0.0.162
User Agent	Mozilla/5.0 (X11; CrOS x86_64 8798.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2858.0 Safari/537.36
Command Line	/opt/google/chrome/chrome --ppapi-flash-path=/opt/google/chrome/pepper/libpepflashplayer.so --ppapi-flash-version=23.0.0.162-r1 --ui-prioritize-in-gpu-process --use-gl=egl --gpu-sandbox-failures-fatal=yes --enable-logging --log-level=1 --use-cras --enable-wayland-server --user-data-dir=/home/chronos --max-unused-resource-memory-usage-percentage=5 --login-profile=user --has-chromeos-keyboard --default-wallpaper-large=/usr/share/chromeos-assets/wallpaper/default_large.jpg --default-wallpaper-small=/usr/share/chromeos-assets/wallpaper/default_small.jpg --child-wallpaper-large=/usr/share/chromeos-assets/wallpaper/child_large.jpg --child-wallpaper-small=/usr/share/chromeos-assets/wallpaper/child_small.jpg --guest-wallpaper-large=/usr/share/chromeos-assets/wallpaper/guest_large.jpg --guest-wallpaper-small=/usr/share/chromeos-assets/wallpaper/guest_small.jpg --enable-prefixed-encrypted-media --enterprise-enrollment-initial-modulus=15 --enterprise-enrollment-modulus-limit=19 --vmodule=screen_locker=2,webui_screen_locker=2,lock_state_controller=2,webui_login_view=2,power_button_observer=2,*ui/display/chromeos*=1,*ash/display*=1,*ui/ozone*=1,*zygote*=1,*plugin*=2,*chromeos/login/*=1 --login-manager --policy-switches-begin --enable-nacl --policy-switches-end --first-exec-after-boot
Executable Path	/opt/google/chrome/chrome
Profile Path	/home/chronos/u-4305ab597ab8a4b15064c619b34aec2c84439920
Variations	6a89113b-2bdd0794
68ebfce2-eb8cb926
16e0dd70-3f4a17df
31101bd6-f23d1dea
1e528f0f-ca7d8d80
8739b412-4f7edc42
e197bfc9-ca7d8d80
8364a5c2-ca7d8d80
7c1bc906-f55a7974
ba3f87da-1410f10
f049a919-3f4a17df
31362330-ca7d8d80
f15c1c09-ca7d8d80
811bc6bc-d93a0620
5274eb09-3f4a17df
f11437-f23d1dea
a4566d9e-3d47f4f4
2e109477-bcf405c8
9e5c75f1-d357b5f9
8f62251a-f23d1dea
6b121ae7-56423c75
5139837c-3f4a17df
7f8176d9-f23d1dea
f79cb77b-3f4a17df
b7786474-d93a0620
23a898eb-e0e2610f
74df3f1-3f4a17df
7382e39a-3f4a17df
4ea303a6-ffbe6084
24cd6bf8-daaf93cf
7a3692af-bc6856d9
f2e050c6-94cb2461
fe9bec35-80f9a33e
9736de91-ca7d8d80
dbffab5d-f23d1dea
de03e059-5c29eebf
ca314179-ca7d8d80
c5073fab-3f4a17df
867c4c68-3f4a17df
b2f0086-f23d1dea
adda5502-ca7d8d80
d747916f-f23d1dea
3ac60855-486e2a9c
f296190c-96d26288
4442aae2-7158671e
ed1d377-e1cc0f14
75f0f0a0-a5822863
e2b18481-6bdfffe7
e7e71889-e1cc0f14
fe05be5f-486e2a9c
61b920c1-1410f10

**Comment by kzahel** [comment]
Chrome 55! Ok... looks like developer channel
I have a device in developer channel I will pull out. Perhaps some new API change that is breaking it. Thanks for letting me know

**Comment by scheng123** [comment]
how old are you? (just curious the youth of you because you develop great software)

**Comment by kzahel** [comment]
Hi Sheng, that's rather private. But I'm rather old :-) Thanks for all your messages and feedback!

**Comment by scheng123** [comment]
did you fix it yet?

**Comment by scheng123** [comment]
oops

**Comment by scheng123** [comment]
btw, its SImon, not sheng

**Comment by kzahel** [comment]
I found an error in dev channel. I put an update in the store and it should be available in the next few hours.

**Comment by kzahel** [comment]
https://github.com/kzahel/web-server-chrome/commit/f22a394a9aa1f3bf5154c4918a97fa64e852f4fe

**Comment by scheng123** [comment]
what was the error?

**Comment by kzahel** [comment]
I think it was this: https://github.com/kzahel/web-server-chrome/commit/f22a394a9aa1f3bf5154c4918a97fa64e852f4fe
FileError is deprecated

**Comment by scheng123** [comment]
so dev mode changed the api huh? well, the "exception" variable is getting popular, especially in java...
