### ISSUE TITLE
can you add support for php files

### ISSUE THREAD

**Issue by scheng123** [kzahel/web-server-chrome#70]
Hello again, can you add support for php files so it works like apache? Please...

**Comment by kzahel** [comment]
Maybe, if somebody wanted to port php to nacl http://stackoverflow.com/questions/8477239/php-for-native-client-nacl

**Comment by scheng123** [comment]
what does that mean???

**Comment by scheng123** [comment]
makes no sense

**Comment by kzahel** [comment]
It means I have no plan to make this happen unless somebody else wants to
do the work to port PHP to chrome

**Comment by davchana** [comment]
> makes no sense

He means that its a whole new level of code/logic to add support for PHP, as php is a server side language, whereas currently this app serves the client-side languages only, like htm/html/css/js etc.

These all files can also be rendered in a web browser as file://path/to/file.htm, but this app helps us to serve it on http://127.0.0.1.

So, it is not an easy task, and as this is a free project, people are welcome to branch/fork & try to add new features.

**Comment by scheng123** [comment]
Ok, I've got it

**Comment by scheng123** [comment]
Thanks

**Comment by davchana** [comment]
@kzahel Can you please close this issue as adding PHP (or any server side language) support is not possible while staying confined within Chrome-App boundaries.
