### ISSUE TITLE
Unhandled request. Did you select a folder to serve?

### ISSUE THREAD

**Issue by Leon121** [kzahel/web-server-chrome#71]
I don't understand what's happening, I have an index.html with a form pointing at a processform.py script in the same folder. I have selected this folder for the server, but it gives me this error:
_Unhandled request. Did you select a folder to serve?_
Please, help.
Thanks,
Leo

**Comment by kzahel** [comment]
Can you open a new tab and put in chrome://version and paste in the info you get

**Comment by Leon121** [comment]
Hi Kzahel, Thank you for replying so quickly! 

Now I'm getting this message:

"External Protocol Request
Google Chrome OS does not support launching an external application to handle localhost links. The link requested is localhost:8887/processform.py"

I am very new to Google Chrome, so I don't know how to get the version, but this laptop is few days old so I guess it has the lastest OS version, whichever that is.

**Comment by kzahel** [comment]
<img width="465" alt="screen shot 2016-09-28 at 7 09 01 pm" src="https://cloud.githubusercontent.com/assets/158352/18938657/10cfe91e-85af-11e6-8377-b68bb1eb1acc.png">

I need to know which version of chrome and OS etc so that I can try and figure out what might cause the problem... because I don't see it on any of my computers.

You should be able to open a new tab and type chrome://version into a tab, and then you can copy and paste that information here, or take a screenshot

**Comment by Leon121** [comment]
Oh, I see, ok this is what I got:

Google Chrome	53.0.2785.103 (Official Build) (64-bit)
Revision	303f356b3441ee792fbd8a53a492eb9280c5e9e6-refs/branch-heads/2785@{#845}
Platform	8530.81.0 (Official Build) stable-channel terra
Blink	537.36 (@303f356b3441ee792fbd8a53a492eb9280c5e9e6)
JavaScript	V8 5.3.332.43
Flash	22.0.0.209-r1
User Agent	Mozilla/5.0 (X11; CrOS x86_64 8530.81.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.103 Safari/537.36

**Comment by Leon121** [comment]
I have done it just now. Thanks!

**Comment by kzahel** [comment]
Ok everything looks good to me there. Did you click on Choose Folder button in the app? And choose a directory? And you still get the error "unhandled request..."

**Comment by Leon121** [comment]
I have chosen a directory yes, and now this is the message I get:
_"External Protocol Request
Google Chrome OS does not support launching an external application to handle localhost links. The link requested is localhost:8887/processform.py"_

**Comment by kzahel** [comment]
Ok, can you maybe try opening a new browser tab, and typing in the URL: http://127.0.0.1:8887/

**Comment by Leon121** [comment]
I have, and it automatically opens my index.html file with my form pointing at my python script "processform.py" and then as soon as I click on the submit button it gives me the message I pasted above...

**Comment by kzahel** [comment]
Oh, okay. Well I think the problem you're having is beyond the scope of what I can help you with. This project only serves static files. It cannot do any dynamic form processing out of the box. You might need to use Apache or something else. On a chromebook, you can look into using "crouton" which can let you install that.

**Comment by Leon121** [comment]
Oh ok, I will try that. Thank you so much for your help and time.

**Comment by kzahel** [comment]
👍
