### ISSUE TITLE
Why the link is 404?

### ISSUE THREAD

**Issue by Ping1122** [kzahel/web-server-chrome#74]
https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb

**Comment by kzahel** [comment]
Google by mistake seems to have disabled my webstore account. It may be a day or two until they can reactive my account. 
:-(

**Comment by kzahel** [comment]
Account was reinstated, but now they need to do a manual review of the app. Might be another day or so...

**Comment by panezhang** [comment]
Wish it won't be too long

**Comment by kzahel** [comment]
and it's back :-)
