### ISSUE TITLE
is http://localhost supported? or it is an easy fix?

### ISSUE THREAD

**Issue by davchana** [kzahel/web-server-chrome#75]
Hi, at the moment server works perfectly at http://127.0.0.1, but for Javascript Service Workers, Chrome need Secure Origins (HTTPS basically), and https on local server in chrome web app is difficult to implement.

But can http://localhost be implemented?, because chrome treats it as secure origin.

https://www.chromium.org/blink/serviceworker/service-worker-faq

**Comment by kzahel** [comment]
Service workers work on http://localhost:{any port} but don't work on http://127.0.0.1:{any port} ?
really?
I haven't really tested http://localhost:8887 etc. But I seem to remember there is maybe no host alias for localhost pointing to the loopback address (127.0.0.1). I don't have a chromeOS device currently. Can you send a screenshot of what happens or something?

**Comment by davchana** [comment]
> Service workers work on http://localhost:{any port} but don't work on http://127.0.0.1:{any port} ?
really?

i will google & will update here. I am sure that Service Workers work on http://localhost , but will check & report with http://127.0.0.1

And Sorry, I was using the port 80 instead of 8887. Please mark this issue as solved/sorted. Server works with both 127.. & localhost with port 8887.
