### ISSUE TITLE
Does it serve/render only index.html, not index.htm?

### ISSUE THREAD

**Issue by davchana** [kzahel/web-server-chrome#76]
I have ticked the option "Automatically show index.html". & I have few folders with index.htm in them, but it just displays the directory listing, & index.htm does not get served. Same file If I rename to index.html (notice L in the end of extension), it gets served fine.

So, does this app/server assumes only .html files are to be shown, not index.htm?

**Comment by kzahel** [comment]
That sounds right, it only serves index.html, not index.htm
I can change this in a future release to also show index.htm if you think that makes sense

**Comment by davchana** [comment]
Yes, please, because many times because of windows 8.3 file naming convention (& also because of habit), .html gets converted to .htm. Appache & other web-servers show index.htm/html/php/anything; I understand here we can not show/process the scripting language like .php; but .htm & .html should be there. Thanks..

**Comment by kzahel** [comment]
I updated the webstore app to 0.4.4. You should probably get it updated within the hour (or sooner if you go to chrome://extensions and click on developer and check for updates or something like that)
https://github.com/kzahel/web-server-chrome/commit/291ef9b83d057e68227b02b626d579fcc118b2e2

**Comment by davchana** [comment]
Wow thats so quick.. i thought it will be done in a week or like that, but you are the man.

I myself tried to go through some code, saw index.html and index.js, but could not find the relevant section..

I am on mobile Chrome now, but will check tomorrow morning on pc..

Thanks much..
