### ISSUE TITLE
why not support auto reload ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [kzahel/web-server-chrome#77]
I just wonder, Why it not support auto reload(refresh) ?

After every time modify, I have to reload the file by refresh the brwoser!

**May be you should add this function!**

**Comment by kzahel** [comment]
That might be a nice option.
How do you think it could be implemented?
I inject a script tag to each html page served that opens a websocket to the server and then waits for a change to the modified time on the file and then refreshes?
Hmm looks like there is no API for filesystem to get inotify events
https://bugs.chromium.org/p/chromium/issues/detail?id=465600

So probably not going to happen.

**Comment by davchana** [comment]
Auto reload is not a good idea IMHO. How will server know when to refresh? Every x minutes? What if I am in the middle of coding, the page rendering will break? What if X is too small number, and its mindlessly refreshing the page? What is its big, and it wastes time to refresh? How is this better than pressing `F5` when required?

**Comment by davchana** [comment]
Also, I do not want any external code added to my pages. And which other main stream server does this? All auto-refreshes are via code always, in programmer's files.

If user needs auto-reload, they can get it easily with meta, javascript etc.

**Comment by kzahel** [comment]
Yeah I agree. Thanks for the advice.
