### ISSUE TITLE
Will this stop working when chrome apps are discontinued?

### ISSUE THREAD

**Issue by olensmar** [kzahel/web-server-chrome#78]
Although this shows up as an extension in the chrome webstore it seems to be defined as an app in the manifest - so I'm curious if it will eventually be discontinued as chrome app support is discontinued (in line with https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html)!?

Thanks for any insights... 

/Ole

**Comment by kzahel** [comment]
Good question. I'm not sure.
It will always be available on chrome OS, but it looks like it may go away for other OS in a few years.
But perhaps it is possible Google will make some exceptions for certain apps?
Or perhaps extensions will gain access to certain API (sockets)

We will have to see...

**Comment by olensmar** [comment]
ok - thanks for answering!

**Comment by DanielHerr** [comment]
Running on other platforms should continue to be supported using NW.js: https://nwjs.io/blog/chrome-apps-support/
