### ISSUE TITLE
JSON API

### ISSUE THREAD

**Issue by fjenett** [kzahel/web-server-chrome#81]
Hey, from your comments on #61 i'm guessing there is already an API somewhere … any chance of exposing or documenting it?

Thanks, this extension is really handy! I'm using it in tandem with devtools to teach web development.

**Comment by kzahel** [comment]
Actually still no JSON api yet. But that's a good idea. I'll change it so if you set the request accept header to application/json it will retun json responses instead of html, should be easy!
Glad you're finding it useful
Cheers

**Comment by kzahel** [comment]
pushed https://github.com/kzahel/web-server-chrome/commit/bf8d6da51c19f87fbe44082cfdaefb0a7203ab63
Also put version 0.4.5 in the store, should update at some point. Let me know if it works out for you

**Comment by fjenett** [comment]
Great, thanks. Will test asap and report.

**Comment by ethanaobrien** [comment]
@kzahel should this be closed?
