### ISSUE TITLE
can't run in 127.0.0.1:8887

### ISSUE THREAD

**Issue by weilinonline** [kzahel/web-server-chrome#87]
remove folder in workspace

**Comment by kzahel** [comment]
?

**Comment by koukinkou** [comment]
mee too,chrome version is 55.0.2883.87 m (64-bit),ERR_CONTENT_LENGTH_MISMATCH

**Comment by kzahel** [comment]
Hmm. Html file are assumed to be utf8 improperly. Am not reading html meta
tags or XML encoding. Can you send example file that gives mismatch

**Comment by weilinonline** [comment]
kill the process. now is ok.
