### ISSUE TITLE
html/php include file not working. index.php file is not open by default

### ISSUE THREAD

**Issue by esuresh19387** [kzahel/web-server-chrome#99]
Hi,
i tried to include separate footer, header php file. But its not displaying. But it is working in wamp server, besides index.php not displaying , just it displaying its directory, after that need to select index.php file, then its working.

Accessible on internet options also is not working.

**Comment by davchana** [comment]
See https://github.com/kzahel/web-server-chrome/issues/70 PHP/ANy-server-side language not supported, is not possible (without some heavy works).

**Comment by kzahel** [comment]
Sorry it does not support PHP. You could use https://termux.com if you have a chromebook with android support along with https://chrome.google.com/webstore/detail/connection-forwarder/ahaijnonphgkgnkbklchdhclailflinn
